### ISSUE TITLE
"Initial Wait" in Lockin_sweep does not work

### ISSUE THREAD

**Issue by Yh-lab** [levylabpitt/Transport#21]
"Initial Wait" in Lockin_sweep programs does not work. The reason is that option is not wired up and the wait time is always 1 s. See second figure.
![image](https://user-images.githubusercontent.com/62907566/98586633-fa9d8c80-2296-11eb-82c9-93f6548363a1.png)
 
![image](https://user-images.githubusercontent.com/62907566/98586657-01c49a80-2297-11eb-88bb-035b3ba1ae9e.png)

**Comment by ciozi137** [comment]
@Yh-lab it does not work like that. The wait happens inside the Lockin. The 1 second wait you are looking at is just to make sure that the lockin has started sweeping
