### ISSUE TITLE
Lockin_sweep can't use alone

### ISSUE THREAD

**Issue by Yh-lab** [levylabpitt/Transport#22]
Lockin_sweep program can only be used with sweep control. When it used alone, the data can not be found in the experiment folder specified in Lockin_sweep program.

**Comment by ciozi137** [comment]
- Fix 1: "OR" in Increment Filename:
![image](https://user-images.githubusercontent.com/26659428/98852981-7bd75980-2426-11eb-8573-410b65716da0.png)

- Fix 2: If Run = Top Level, don't append data 
![image](https://user-images.githubusercontent.com/26659428/98853052-8f82c000-2426-11eb-8cbc-4030e93786b3.png)

**Comment by ciozi137** [comment]
Fix 1 fixed in File Utilities v1.2.6
