### ISSUE TITLE
Lockin_sweep sweep start & end sidegate voltage different from the set values

### ISSUE THREAD

**Issue by Yh-lab** [levylabpitt/Transport#23]
For example, the set values are -25 mV and 200 mV. But in the set time, it only goes from -25 mV to 90 mV
![image](https://user-images.githubusercontent.com/62907566/98843745-5abc3c00-2419-11eb-954c-ad2ce92facf6.png)
![image](https://user-images.githubusercontent.com/62907566/98843772-64de3a80-2419-11eb-982b-aa2946d9c94c.png)

**Comment by ciozi137** [comment]
Check DAQ: Process and come up with more reliable method to end sweep. Maybe it is timing out? Maybe taking difference of millisecond timer value is not a good idea?

**Comment by ciozi137** [comment]
I think this is fixed in v2.11.10. @Yh-lab please try
