### ISSUE TITLE
PPMS3 lockin-time vi

### ISSUE THREAD

**Issue by ymq526** [levylabpitt/Transport#65]
Lockin-time vi on PPMS3 saves user notes with every datapoint, making the file size very large

**Comment by 1ranjani1** [comment]
Lockin_time used to save .dat files until the recent updates, but now its saving TDMS. @ciozi137 Perhaps this has something to do with that?

**Comment by 1ranjani1** [comment]
![image](https://user-images.githubusercontent.com/86365074/201741779-d76d47b3-d340-4692-a509-ca55e688d447.png)
This is how the file looks.

**Comment by ciozi137** [comment]
@1ranjani1 it is a binary file. It can't be read like that. If I open the TDMS file in Excel or Labview it looks fine

**Comment by 1ranjani1** [comment]
Oops, I'm sorry. It does read fine. But it does not seem to have a column for magnetic field. I think that is why I had issue now. Only time, temperature and channels
![image](https://user-images.githubusercontent.com/86365074/201743823-1f6fb9dd-380d-463c-9c21-26632635e287.png)

**Comment by ciozi137** [comment]
This issue will happen if control experiment is not initialized properly
