### ISSUE TITLE
Sweep Control waveform type

### ISSUE THREAD

**Issue by Sayanwita** [levylabpitt/Transport#82]
Triangle function does not work. It's locally fixed in CF DAQ computer.

**Comment by ciozi137** [comment]
![image](https://github.com/levylabpitt/Transport/assets/26659428/a05aeb98-0aa4-4f1d-b60e-a7661e9854a1)
![image](https://github.com/levylabpitt/Transport/assets/26659428/de8361e5-f31c-4b7d-854b-c9a86e3e6fe8)
![image](https://github.com/levylabpitt/Transport/assets/26659428/a273f4a8-f33f-423c-a01a-dbf1ece77c7f)
