### ISSUE TITLE
Setting up strain sweep

### ISSUE THREAD

**Issue by Sayanwita** [levylabpitt/Transport#90]
![strain_block_diagram](https://github.com/user-attachments/assets/04545904-7762-4cc5-884e-781f2d5dc63a)

![image](https://github.com/user-attachments/assets/f254b339-088c-4902-80a2-3a5219e6391c)

Sweep control>scan action>strain

**Comment by ciozi137** [comment]
@Sayanwita as we discussed I don't think this should be fixed like your proposal, but instead the wiring itself should be changed.

For future reference I would like to approach this problem in the following way through attributes using the following design pattern:

1. Control Experiment sets an instrument/SMO attribute, for example "s/n":
![image](https://github.com/user-attachments/assets/9059fa2b-d0a3-4da1-bfb0-4ac4a4264c16)

2. the attribute is then read inside Scan action.vi to determine the instrument's attribute or class decoration:
![image](https://github.com/user-attachments/assets/1ff4a7d7-9dd0-42e3-88ab-200c5591736f)
